---

config2:
  interface: "{{ config['hosts'] | selectattr('name', '==', inventory_hostname) | first }}"
  peers:     "{{ config['hosts'] | rejectattr('name', '==', inventory_hostname) }}"
  #peers:     "{{ config['hosts'] | rejectattr('name', '==', inventory_hostname) | rejectattr('isolate', 'false') }}"

