---

config2:
  interface: "{{ config['hosts'] | selectattr('name', '==', inventory_hostname) | first | default({}) }}"
  peers:     "{{ config['hosts'] | rejectattr('name', '==', inventory_hostname) | default({}) }}"

